# Netlify configuration for a static site
[build]
  publish = "."

# Security and caching headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "geolocation=(), camera=(), microphone=()"
    # Default caching for HTML
    Cache-Control = "public, max-age=0, must-revalidate"

# Long-term caching for static assets
[[headers]]
  for = "/attached_assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Tip: If you later add strict CSP, whitelist used CDNs (pico css, unpkg, jsdelivr)
# [[headers]]
#   for = "/*"
#   [headers.values]
#     Content-Security-Policy = "default-src 'self'; img-src 'self' https: data:; style-src 'self' 'unsafe-inline' https:; script-src 'self' https:; connect-src 'self'; frame-ancestors 'self'"

# Redirect www → apex and force HTTPS
[[redirects]]
  from = "https://www.aurooms.it/*"
  to = "https://aurooms.it/:splat"
  status = 301
  force = true

# Protect admin pages - only accessible by IP or with specific auth
[[headers]]
  for = "/admin-*"
  [headers.values]
    # Add additional security headers for admin pages
    X-Robots-Tag = "noindex, nofollow, noarchive, nosnippet"
    Cache-Control = "no-cache, no-store, must-revalidate"

# Hide admin pages from search engines and bots
[[redirects]]
  from = "/admin-*"
  to = "/404.html"
  status = 404
  conditions = {Role = ["!admin"]}

# Optional: Create a secret path for admin access (replace 'your-secret-path' with something secure)
[[redirects]]
  from = "/pannello-controllo-aurooms-2025/*"
  to = "/admin-:splat"
  status = 200
