services:
  - type: web
    name: aurooms-backend
    env: python
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.wsgi:app --bind 0.0.0.0:$PORT
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: APP_SECRET
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
